replicas: 4

resources:
  requests:
    cpu: 2000m
    memory: 4Gi
  limits:
    cpu: 4000m
    memory: 8Gi

storage:
  ledger:
    className:
    volumeSize: 100Gi
  journal:
    className:
    volumeSize: 100Gi
  index:
    className:
    volumeSize: 10Gi

jvmOptions:
  memoryOpts: ["-Xms2g", "-XX:MaxDirectMemorySize=4g"]
