replicas: 3

resources:
  requests:
    cpu: 1000m
    memory: 4Gi
  limits:
    cpu: 2000m
    memory: 4Gi

storage:
  ledger:
    className:
    volumeSize: 100Gi
  journal:
    className:
    volumeSize: 100Gi
  index:
    className:
    volumeSize: 10Gi

jvmOptions:
  memoryOpts: ["-Xms1g", "-XX:MaxDirectMemorySize=2g"]
